[formatter.nix]
command = "nixpkgs-fmt"
includes = ["*.nix"]

[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]

[formatter.satysfi]
command = "satysfi-fmt-write-each"
includes = ["*.saty", "*.satyh", "*.satyg"]
